#!/usr/bin/env python3
"""
check_completeness.py — scan all instrument repos for explorer completeness and
update the GitHub tracker issues (#26 Strings, #27 Woodwind, #28 Idiophones,
#29 Percussion).

Completeness criteria (matching the tracker issue legend):
  W  Wolfram model  — explorer.html contains a wolframcloud.com URL
  I  Images         — images/hero-render.{png,jpg} exists in the repo
  3D model viewer   — explorer.html contains <model-viewer or a .gltf/.glb href

Usage:
  python3 scripts/check_completeness.py              # print summary table
  python3 scripts/check_completeness.py --json       # machine-readable snapshot
  python3 scripts/check_completeness.py --update-issues   # edit GitHub tracker issues
  python3 scripts/check_completeness.py --save       # write data/completeness-snapshot.json
"""
import os, re, json, subprocess, argparse
from pathlib import Path
from datetime import datetime

ROOT = "/mnt/c/Users/Tony/Documents/GitHub/instruments"
HERE = Path(__file__).resolve().parent
SNAPSHOT = HERE.parent / "data" / "completeness-snapshot.json"

FAMILIES = [
    ("strings",    "string",    26),
    ("woodwind",   "wind",      27),
    ("idiophones", "idiophone", 28),
    ("percussion", "drum",      29),
    ("brass",      "brass",     None),
]

TRACKER_HEADER = """\
## {title} — explorer completeness tracker

Tracking interactive completeness of each instrument's `explorer.html`. A repo is **complete** when its explorer has a live Wolfram model, rendered concept images, and a 3D viewer.

Legend: ✅ done · ⬜ todo  (W = Wolfram model · I = images · 3D = model viewer)

| Instrument | Wolfram | Images | 3D | Status |
|---|:--:|:--:|:--:|---|
"""


CAD_EXTS = {".sldprt", ".sldasm", ".stl", ".step", ".stp", ".iges", ".igs",
            ".3mf", ".f3d", ".scad", ".dxf", ".glb", ".gltf"}
IMG_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}


def check_wolfram(exp_html):
    return "wolframcloud.com" in exp_html


def check_images(slug_path):
    img_dir = slug_path / "images"
    if not img_dir.is_dir():
        return False
    for f in img_dir.rglob("*"):
        if f.is_file() and f.suffix.lower() in IMG_EXTS:
            return True
    return False


def check_3d(slug_path):
    cad_dir = slug_path / "cad"
    if not cad_dir.is_dir():
        return False
    for f in cad_dir.rglob("*"):
        if f.is_file() and f.suffix.lower() in CAD_EXTS:
            return True
    return False


def scan_family(folder_name):
    fam_path = Path(ROOT) / folder_name
    if not fam_path.is_dir():
        return []
    results = []
    for slug in sorted(os.listdir(fam_path)):
        slug_path = fam_path / slug
        if not slug_path.is_dir():
            continue
        exp = slug_path / "explorer.html"
        if not exp.exists():
            results.append({"slug": slug, "wolfram": False, "images": False, "model3d": False, "has_explorer": False})
            continue
        html = exp.read_text(errors="ignore")
        results.append({
            "slug": slug,
            "wolfram": check_wolfram(html),
            "images": check_images(slug_path),
            "model3d": check_3d(slug_path),
            "has_explorer": True,
        })
    return results


def status_label(r):
    if not r["has_explorer"]:
        return "Scaffold"
    score = sum([r["wolfram"], r["images"], r["model3d"]])
    if score == 3:
        return "**Complete**"
    elif score == 2:
        return "Near"
    elif score == 1:
        return "In progress"
    return "Scaffold"


def build_issue_body(family_title, rows, scan_date):
    ck = lambda b: "✅" if b else "⬜"
    lines = [TRACKER_HEADER.format(title=family_title)]
    for r in rows:
        st = status_label(r)
        lines.append(f"| `{r['slug']}` | {ck(r['wolfram'])} | {ck(r['images'])} | {ck(r['model3d'])} | {st} |")
    complete = sum(1 for r in rows if status_label(r) == "**Complete**")
    lines.append(f"\n**{complete}/{len(rows)} complete.** Regenerated by `check_completeness.py` on {scan_date}.")
    return "\n".join(lines)


def update_issue(issue_num, body):
    result = subprocess.run(
        ["gh", "issue", "edit", str(issue_num), "--repo", "tonykoop/instrument-showcase", "--body", body],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"  ERROR updating issue #{issue_num}: {result.stderr.strip()}")
    else:
        print(f"  updated issue #{issue_num}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", action="store_true", help="emit JSON snapshot")
    parser.add_argument("--update-issues", action="store_true", help="edit GitHub tracker issues")
    parser.add_argument("--save", action="store_true", help="write data/completeness-snapshot.json")
    args = parser.parse_args()

    scan_date = datetime.utcnow().strftime("%Y-%m-%d")
    snapshot = {"generated_at": scan_date, "families": {}}

    for folder_name, lib_name, issue_num in FAMILIES:
        rows = scan_family(folder_name)
        complete = sum(1 for r in rows if status_label(r) == "**Complete**")
        snapshot["families"][folder_name] = {
            "total": len(rows),
            "complete": complete,
            "rows": rows,
        }
        title = folder_name.capitalize()
        print(f"{title}: {complete}/{len(rows)} complete")
        for r in rows:
            st = status_label(r)
            if not args.json:
                w = "W" if r["wolfram"] else " "
                i = "I" if r["images"] else " "
                d = "3" if r["model3d"] else " "
                print(f"  [{w}{i}{d}] {r['slug']} — {st}")

        if args.update_issues and issue_num:
            body = build_issue_body(title, rows, scan_date)
            update_issue(issue_num, body)

    if args.json:
        print(json.dumps(snapshot, indent=2))

    if args.save:
        SNAPSHOT.parent.mkdir(exist_ok=True)
        SNAPSHOT.write_text(json.dumps(snapshot, indent=2))
        print(f"\nwrote {SNAPSHOT}")


if __name__ == "__main__":
    main()
